// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyrGCctjij_-omrM3EYsXP163mJQjz-PY',
    appId: '1:290452992296:web:97c6e3f75aa258f9b5e01d',
    messagingSenderId: '290452992296',
    projectId: 'just-halal-b48e6',
    authDomain: 'just-halal-b48e6.firebaseapp.com',
    databaseURL: 'https://just-halal-b48e6-default-rtdb.firebaseio.com',
    storageBucket: 'just-halal-b48e6.appspot.com',
    measurementId: 'G-5R6XQE8XJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqFEHoIYP-n0fpACoAETmzOy_nDNx52XY',
    appId: '1:290452992296:android:b01c11bb26287862b5e01d',
    messagingSenderId: '290452992296',
    projectId: 'just-halal-b48e6',
    databaseURL: 'https://just-halal-b48e6-default-rtdb.firebaseio.com',
    storageBucket: 'just-halal-b48e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_iDE35aOWncfhA7Hso5r-XroAjOORGS4',
    appId: '1:290452992296:ios:a851a70fa4f22f94b5e01d',
    messagingSenderId: '290452992296',
    projectId: 'just-halal-b48e6',
    databaseURL: 'https://just-halal-b48e6-default-rtdb.firebaseio.com',
    storageBucket: 'just-halal-b48e6.appspot.com',
    iosBundleId: 'com.aethon.halalapp.halalApp',
  );
}
